[package]
authors = ["Crypto Garage"]
name = "bitcoin-test-utils"
version = "0.0.1"

[dependencies]
bitcoin = {version = "0.26.0"}
bitcoincore-rpc = {version = "0.13.0"}
bitcoincore-rpc-json = {version = "0.13.0"}
