[package]
name = "bitcoin-test-utils"
version = "0.0.1"
authors = ["Crypto Garage"]

[dependencies]
bitcoin = {version="0.25.2-adaptor.0", git = "https://github.com/p2pderivatives/rust-bitcoin", branch = "ecdsa-adaptor", package="bitcoin"}
