[package]
name = "dlc-messages"
version = "0.0.1"
authors = ["Crypto Garage"]

[features]
use-serde = ["serde", "bitcoin/serde", "secp256k1/serde"]

[dependencies]
bitcoin = {version="0.25.2-adaptor.0", git = "https://github.com/p2pderivatives/rust-bitcoin", branch = "ecdsa-adaptor", package="bitcoin"}
secp256k1 = {version="0.19.0-adaptor.0", git = "https://github.com/p2pderivatives/rust-secp256k1", branch = "ecdsa-adaptor", package="secp256k1"}
lightning = {version="0.0.12-adaptor.0", git = "https://github.com/p2pderivatives/rust-lightning", branch= "ecdsa-adaptor"}
serde = { version = "1", features = ["derive"], optional = true }
unicode-normalization = { version = "0.1.16" }
dlc = { version = "0.0.1", path = "../dlc" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
bitcoin = { version="0.25.2-adaptor.0", git = "https://github.com/p2pderivatives/rust-bitcoin", branch = "ecdsa-adaptor", package="bitcoin", features=["use-serde"] }
secp256k1 = { version="0.19.0-adaptor.0", git = "https://github.com/p2pderivatives/rust-secp256k1", branch = "ecdsa-adaptor", package="secp256k1", features=["serde"] } 
