on: [push, pull_request]

name: Continuous integration

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  integration_tests_prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: cargo test --no-run && echo "::set-output name=matrix::$(scripts/generate_integration_tests_list.sh)"
  integration_tests:
    name: integration-tests
    needs: integration_tests_prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests: ${{ fromJson(needs.integration_tests_prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Start bitcoin node
        run: ./scripts/start_node.sh
      - name: Run test
        run: cargo test -- --ignored ${{ matrix.tests }}
      - name: Stop bitcoin node
        run: ./scripts/stop_node.sh
